#Generating Random Numbers

In [2]:
 import numpy as np


income = np.round(np.random.normal(250, 23.99393, 20), 2) # generate random numbers for some normal distribution 
#age =  np.random.randint(2, size=100)
age = np.random.randint(low = 20, high= 35, size=20)  #this code generate random numbers between 20 and 35

inc_ageRatio = np.column_stack((income, age))    # 



#inc_ageRatio.size
inc_ageRatio.shape
#inc_ageRatio

#agecol = np.array(inc_ageRatio[:, 1])
#agecol




(20, 2)

In [4]:
type(age)
age.tolist()

[27,
 33,
 24,
 21,
 31,
 28,
 28,
 27,
 26,
 22,
 25,
 21,
 25,
 25,
 27,
 31,
 20,
 24,
 22,
 20]

In [34]:
np.mean(inc_ageRatio[])

141.21674999999999

In [43]:
inc_ageRatio[0, :]

array([ 215.75,   22.  ])

In [50]:
lastone = inc_ageRatio
lastone

array([[ 215.75,   22.  ],
       [ 215.68,   28.  ],
       [ 266.79,   22.  ],
       [ 242.04,   29.  ],
       [ 252.9 ,   22.  ],
       [ 287.02,   32.  ],
       [ 273.42,   28.  ],
       [ 214.92,   28.  ],
       [ 246.19,   32.  ],
       [ 226.41,   24.  ],
       [ 239.06,   20.  ],
       [ 226.4 ,   34.  ],
       [ 251.7 ,   21.  ],
       [ 232.2 ,   26.  ],
       [ 267.14,   21.  ],
       [ 250.41,   28.  ],
       [ 274.11,   27.  ],
       [ 214.44,   30.  ],
       [ 288.5 ,   26.  ],
       [ 251.98,   32.  ]])

In [51]:
lastone

array([[ 215.75,   22.  ],
       [ 215.68,   28.  ],
       [ 266.79,   22.  ],
       [ 242.04,   29.  ],
       [ 252.9 ,   22.  ],
       [ 287.02,   32.  ],
       [ 273.42,   28.  ],
       [ 214.92,   28.  ],
       [ 246.19,   32.  ],
       [ 226.41,   24.  ],
       [ 239.06,   20.  ],
       [ 226.4 ,   34.  ],
       [ 251.7 ,   21.  ],
       [ 232.2 ,   26.  ],
       [ 267.14,   21.  ],
       [ 250.41,   28.  ],
       [ 274.11,   27.  ],
       [ 214.44,   30.  ],
       [ 288.5 ,   26.  ],
       [ 251.98,   32.  ]])

In [52]:
np.mean(lastone)

136.72649999999999

In [53]:
np.mean(lastone[:, 1])

26.600000000000001

In [55]:
#corellation co-efficient

np.corrcoef(lastone[:, 0], lastone[:, 1])

array([[ 1.        , -0.04973076],
       [-0.04973076,  1.        ]])