In [10]:
import numpy as np

height = ([56, 45, 34, 76, 100])
np_height = np.array(height)
np_height
wieght = ([100, 130, 210, 132, 140])
    
np_wieght  =  np.array(wieght)

bmi = np_wieght / np_height ** 2
bmi <1



array([ True,  True,  True,  True,  True], dtype=bool)

In [11]:
bmi[bmi<1]

array([ 0.03188776,  0.06419753,  0.1816609 ,  0.02285319,  0.014     ])

In [12]:
bmi >1 

array([False, False, False, False, False], dtype=bool)

In [14]:
bmi[bmi>1]

array([], dtype=float64)

In [ ]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np


# Create a Numpy array from baseball: np_baseball
np_baseball 

# Print out type of np_baseball
