In [95]:
import numpy as np

#first create a one-d numpy array

firstNames = ([ 'jeff', 'james', 'johnson', 'robert'])
lastNames = (['Ansah', 'Nwi-tanoe', 'sirelaf-ellem', 'nii-addo'])
names = np.column_stack((firstName,lastNames))
names.shape






(4, 2)

In [57]:
names[0]
names[1]
names[1, 3]
names[:, 1]   # this prints out james tanoe
names[:, 3]
names[:, 0:2]


array([['jeff', 'james'],
       ['Ansah', 'Nwi-tanoe']], 
      dtype='<U13')

In [84]:
players= ([67, 56], [67, 46], [65, 66], [44, 89], [78, 79] , [70, 77], [76, 79])
np_players = np.array(players)
np_players.shape


(7, 2)

In [85]:
np_players

array([[67, 56],
       [67, 46],
       [65, 66],
       [44, 89],
       [78, 79],
       [70, 77],
       [76, 79]])

In [86]:
np_players[3, :]

array([44, 89])

In [87]:
np_players * 2

array([[134, 112],
       [134,  92],
       [130, 132],
       [ 88, 178],
       [156, 158],
       [140, 154],
       [152, 158]])

In [89]:
# performing operations on arrays: This code multiple the first coloum of the array by 0 and the colun

np_players + np.array([3,20])
np_players.shape
np_players

array([[67, 56],
       [67, 46],
       [65, 66],
       [44, 89],
       [78, 79],
       [70, 77],
       [76, 79]])

In [90]:
tryplayers= ([67, 56, 56], [67, 46,213], [65, 66,54], [44, 89,21], [78, 79,132] , [70, 77,232], [76, 79,231])
lnp_players = np.array(tryplayers)
lnp_players.shape
lnp_players



array([[ 67,  56,  56],
       [ 67,  46, 213],
       [ 65,  66,  54],
       [ 44,  89,  21],
       [ 78,  79, 132],
       [ 70,  77, 232],
       [ 76,  79, 231]])

In [92]:
lnp_players + np.array([0, 0, 1])

array([[ 67,  56,  57],
       [ 67,  46, 214],
       [ 65,  66,  55],
       [ 44,  89,  22],
       [ 78,  79, 133],
       [ 70,  77, 233],
       [ 76,  79, 232]])

In [93]:
tryplayers + np_players

ValueError: operands could not be broadcast together with shapes (7,3) (7,2) 